DROP TABLE IF EXISTS seeker;
DROP TABLE IF EXISTS announce;
DROP TABLE IF EXISTS announcer;
DROP TABLE IF EXISTS departements;
DROP TABLE IF EXISTS regions;



CREATE TABLE IF NOT EXISTS regions (
  id TINYINT(2) UNSIGNED NOT NULL,
  name VARCHAR(256) NOT NULL DEFAULT '',
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS departements (
  id CHAR(3) NOT NULL,
  name VARCHAR(32) NOT NULL,
  region_id TINYINT(2) UNSIGNED NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (region_id) REFERENCES regions (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS announcer (
  name VARCHAR(32) NOT NULL,
  adresse VARCHAR(32) NOT NULL,
  email VARCHAR(32) NOT NULL,
  PRIMARY KEY (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS announce(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  announcer VARCHAR(32) NOT NULL,
  short_description VARCHAR(32) NOT NULL,
  long_description VARCHAR(256) NOT NULL,
  type CHAR(3) NOT NULL,
  start_date DATE,
  end_date DATE,
  job VARCHAR(32) NOT NULL,
  region_id TINYINT(2) UNSIGNED NOT NULL,
  departement_id CHAR(3) NOT NULL,
  adress VARCHAR(32),
  PRIMARY KEY (id),
  FOREIGN KEY (region_id) REFERENCES regions (id),
  FOREIGN KEY (departement_id) REFERENCES departements (id),
  FOREIGN KEY (announcer) REFERENCES announcer (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

 CREATE TABLE IF NOT EXISTS seeker (
   first_name VARCHAR(16) NOT NULL,
   last_name VARCHAR(16) NOT NULL,
   email VARCHAR(32) NOT NULL,
   phone_number INT(10) UNSIGNED NOT NULL,
   departement_id CHAR(3) NOT NULL,
   region_id TINYINT(2) UNSIGNED NOT NULL,
   adress VARCHAR(32),
   FOREIGN KEY (departement_id) REFERENCES departements (id),
   FOREIGN KEY (region_id) REFERENCES regions (id)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;



 INSERT INTO  regions (id, name)
      VALUES  (1, 'Alsace'),
              (2, 'Aquitaine'),
              (3, 'Auvergne'),
              (4, 'Bourgogne'),
              (5, 'Bretagne'),
              (6, 'Centre'),
              (7, 'Champagne-Ardenne'),
              (8, 'Corse'),
              (9, 'Franche-Comté'),
              (10, 'Île-de-France'),
              (11, 'Languedoc-Roussillon'),
              (12, 'Limousin'),
              (13, 'Lorraine'),
              (14, 'Midi-Pyrénées'),
              (15, 'Nord-Pas-de-Calais'),
              (16, 'Basse-Normandie'),
              (17, 'Haute-Normandie'),
              (18, 'Pays de la Loire'),
              (19, 'Picardie'),
              (20, 'Poitou-Charentes'),
              (21, 'Provence-Alpes-Côte d\'Azur'),
              (22, 'Rhône-Alpes'),
              (23, 'Guyane'),
              (24, 'Guadeloupe'),
              (25, 'Martinique'),
              (26, 'Réunion');

 INSERT INTO  departements (id, name, region_id)
      VALUES  ('01', 'Ain', 22),
              ('02', 'Aisne', 19),
              ('03', 'Allier', 3),
              ('04', 'Alpes-de-Haute-Provence', 21),
              ('05', 'Hautes-Alpes', 21),
              ('06', 'Alpes-Maritimes', 21),
              ('07', 'Ardèche', 22),
              ('08', 'Ardennes', 7),
              ('09', 'Ariège', 14),
              ('10', 'Aube', 7),
              ('11', 'Aude', 11),
              ('12', 'Aveyron', 14),
              ('13', 'Bouches-du-Rhône', 21),
              ('14', 'Calvados', 16),
              ('15', 'Cantal', 3),
              ('16', 'Charente', 20),
              ('17', 'Charente-Maritime', 20),
              ('18', 'Cher', 6),
              ('19', 'Corrèze', 12),
              ('2A', 'Corse-du-Sud', 8),
              ('2B', 'Haute-Corse', 8),
              ('21', 'Côte-d\'Or', 4),
              ('22', 'Côtes-d\'Armor', 5),
              ('23', 'Creuse', 12),
              ('24', 'Dordogne', 2),
              ('25', 'Doubs', 9),
              ('26', 'Drôme', 22),
              ('27', 'Eure', 17),
              ('28', 'Eure-et-Loir', 6),
              ('29', 'Finistère', 5),
              ('30', 'Gard', 11),
              ('31', 'Haute-Garonne', 14),
              ('32', 'Gers', 14),
              ('33', 'Gironde', 2),
              ('34', 'Hérault', 11),
              ('35', 'Ille-et-Vilaine', 4),
              ('36', 'Indre', 6),
              ('37', 'Indre-et-Loire', 6),
              ('38', 'Isère', 22),
              ('39', 'Jura', 9),
              ('40', 'Landes', 2),
              ('41', 'Loir-et-Cher', 6),
              ('42', 'Loire', 22),
              ('43', 'Haute-Loire', 3),
              ('44', 'Loire-Atlantique', 18),
              ('45', 'Loiret', 6),
              ('46', 'Lot', 14),
              ('47', 'Lot-et-Garonne', 2),
              ('48', 'Lozère', 11),
              ('49', 'Maine-et-Loire', 18),
              ('50', 'Manche', 16),
              ('51', 'Marne', 7),
              ('52', 'Haute-Marne', 7),
              ('53', 'Mayenne', 18),
              ('54', 'Meurthe-et-Moselle', 13),
              ('55', 'Meuse', 13),
              ('56', 'Morbihan', 5),
              ('57', 'Moselle', 13),
              ('58', 'Nièvre', 4),
              ('59', 'Nord', 15),
              ('60', 'Oise', 19),
              ('61', 'Orne', 16),
              ('62', 'Pas-de-Calais', 15),
              ('63', 'Puy-de-Dôme', 3),
              ('64', 'Pyrénées-Atlantiques', 2),
              ('65', 'Hautes-Pyrénées', 14),
              ('66', 'Pyrénées-Orientales', 11),
              ('67', 'Bas-Rhin', 1),
              ('68', 'Haut-Rhin', 1),
              ('69', 'Rhône', 22),
              ('70', 'Haute-Saône', 9),
              ('71', 'Saône-et-Loire', 4),
              ('72', 'Sarthe', 18),
              ('73', 'Savoie', 22),
              ('74', 'Haute-Savoie', 22),
              ('75', 'Paris', 10),
              ('76', 'Seine-Maritime', 17),
              ('77', 'Seine-et-Marne', 10),
              ('78', 'Yvelines', 10),
              ('79', 'Deux-Sèvres', 20),
              ('80', 'Somme', 19),
              ('81', 'Tarn', 14),
              ('82', 'Tarn-et-Garonne', 14),
              ('83', 'Var', 21),
              ('84', 'Vaucluse', 21),
              ('85', 'Vendée', 18),
              ('86', 'Vienne', 20),
              ('87', 'Haute-Vienne', 12),
              ('88', 'Vosges', 13),
              ('89', 'Yonne', 4),
              ('90', 'Territoire de Belfort', 9),
              ('91', 'Essonne', 10),
              ('92', 'Hauts-de-Seine', 10),
              ('93', 'Seine-Saint-Denis', 10),
              ('94', 'Val-de-Marne', 10),
              ('95', 'Val-d\'Oise', 10),
              ('971', 'Guadeloupe', 24),
              ('972', 'Martinique', 25),
              ('973', 'Guyane', 23),
              ('974', 'La Réunion', 26);
